name: Game Request
description: Suggest a game for this project to support
title: "[Game]:"
labels: ['enhancement']
assignees: Furglitch
body:
  - type: input
    id: game
    attributes:
      label: Game Title
      description: Which game do you want functionality added for?
      placeholder: 'Skyrim Hologram Edition'
    validations:
      required: true
  - type: checkboxes
    id: support
    attributes:
      label: MO2 Support
      description: Is this game supported by MO2
      options:
        - label: "Yes, a full release (i.e. 2.5.2)"
        - label: "Yes, a development build (i.e. 2.5.3dev3 or beta1)"
        - label: "Yes, but requires the [modorganizer-basic_games](https://github.com/ModOrganizer2/modorganizer-basic_games) plugin"
        - label: "No"
    validations:
      required: true